version: '3.5'

services:
    service.local:
        build:
            context: .
            dockerfile: Dockerfile.qa
        container_name: service.local
        ports: 
            - "80:80"
        networks:
            - default
