version: '3.5'

services:
    service.local:
        build:
            context: .
            dockerfile: Dockerfile.local
        container_name: service.local
        ports: 
            - "80:80"
        networks:
            - default
        volumes:
            - ./app/:/app
        env_file:
            - ./service.env
