version: '3.5'

services:
    example.local:
        build:
            context: .
            dockerfile: Dockerfile.local
        container_name: example.local
        ports: 
            - "8002:80"
        networks:
            - default
        volumes:
            - ./src/:/app
        env_file:
            - ./service.env
